### ISSUE TITLE
Frontend: Structure the src folder according to coding standard

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#14]
Like, components, container, routes,...

**Comment by codewithvk** [comment]
Can you assign me @AkbarHabeeb?

**Comment by Aaryan8751** [comment]
@AkbarHabeeb could you please assign me this work also?

**Comment by AkbarHabeeb** [comment]
Please go ahead @Aaryan8751

**Comment by AkbarHabeeb** [comment]
Deferred #32
