### ISSUE TITLE
Add a Navbar with project title

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#17]
A plain Navbar alone is enough. You can use reactstrap or anyother UI library.
Ref: ![Sample design](https://github.com/Team-Tomato/QP-Generator/blob/master/Asset/Images/Ref-navbar.png)

**Comment by anushkasinghal11** [comment]
Hey!
I am interested to work on this issue

**Comment by Aaryan8751** [comment]
@AkbarHabeeb could you please assign me this work also?

**Comment by AkbarHabeeb** [comment]
Already made the changes 👍 Encouraging you to solve the assigned issue

**Comment by AkbarHabeeb** [comment]
Duplicate of #4

**Comment by AkbarHabeeb** [comment]
@anushkasinghal11 Please pull the latest changes and try if you can improve the navbar

**Comment by AkbarHabeeb** [comment]
Lot to be improved in the navbar section @codewithvk 
Assigning it to @anushkasinghal11, please improvise the changes and feel free to structure them to the standards

**Comment by codewithvk** [comment]
@AkbarHabeeb can you tell me what should change you want?

**Comment by AkbarHabeeb** [comment]
Appreciate your interest @codewithvk, will ping the details. tonight

**Comment by AkbarHabeeb** [comment]
Resolved #33 
@anushkasinghal11 Next time, please update on the same PR. No need to rise it seperately. Keep learning
