### ISSUE TITLE
Adding text box and button components

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#19]
In QP tab,
Create a text box that has a + button next to it. Clicking on the + should add another text box. Similarly, clicking on the - button against the textbox should remove the text box. 

post that give a try for https://github.com/Team-Tomato/QP-Generator/issues/20

**Comment by tejaswini22199** [comment]
I want to work on this issue. Could you assign it to me.

**Comment by AkbarHabeeb** [comment]
You can get started here @tejaswini22199

**Comment by AkbarHabeeb** [comment]
Intiated the project
