### ISSUE TITLE
Design a help page which lists the list of things to be done for this project

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#2]

**Comment by codewithvk** [comment]
Can you give more description?

**Comment by AkbarHabeeb** [comment]
Hi @codewithvk 

Initialize the project and just show the list of components(as a text) which we have planned to use. A simple help page. 
Just initialize the project, post that I can help you for sure @codewithvk

**Comment by Kishor-Kumar07** [comment]
Hii @AkbarHabeeb Any issue that I can work on?

**Comment by AkbarHabeeb** [comment]
You can check #20 @Kishor-Kumar07

**Comment by AkbarHabeeb** [comment]
Achieved already.
