### ISSUE TITLE
Could you please host this project.

### ISSUE THREAD

**Issue by Vishal-raj-1** [Team-Tomato/QP-Generator#37]
**Describe the solution you'd like**

@AkbarHabeeb Sir,  It will be easy for all to check the bugs without forking the repo. Or comparing with their repo with this. Kindly host this project either on netlify or github.

**Comment by AkbarHabeeb** [comment]
Will do it in 2 days @Vishal-raj-1 , granted 2 points for suggesting the idea in the issue.

**Comment by Tejas1510** [comment]
@AkbarHabeeb Can i do

**Comment by AkbarHabeeb** [comment]
We have deployed our initial site, it will be really good if u can read our wiki page and check the site https://qp-generator.netlify.app/#/ to start working on it. Thanks @Tejas1510 and @Vishal-raj-1
