### ISSUE TITLE
Add Gitpod support

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#39]
Add gitpod and update the readme with its details

**Comment by tejaswini22199** [comment]
can i work on this @AkbarHabeeb

**Comment by tamilarasumk731** [comment]
@tejaswini22199 I have already done the task.
But I didn't comment here. 

CC: @AkbarHabeeb

**Comment by tejaswini22199** [comment]
okay

**Comment by tamilarasumk731** [comment]
Closing the Issue.

CC: @AkbarHabeeb @InbasasiS @smartsri18
