### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#4]
Remove the default react app view and add a Navbar showing the project title.
- Show a dropdown which fetches show options which are from a config file, based on the selection in dropdown it should fill the below 3 text boxes with the data from the config file. (U can use any data)
Eg: Selecting subject code should auto fill the staff name and subject name

**Comment by codewithvk** [comment]
Can we use any react Ui library?

If yes then please tell me which library is preferable for this project.

**Comment by AkbarHabeeb** [comment]
Feel free to use any popular react UI lib, eg: material Ui, reactstrap. And avoid using any unpopular packages which might cause unsupport issue in near future. @codewithvk

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @AkbarHabeeb . I want to work on this

**Comment by AkbarHabeeb** [comment]
Assigned, Let us know if u have any doubt or questions @subhangi2731

**Comment by AkbarHabeeb** [comment]
Do we have any updates @subhangi2731 and @codewithvk

**Comment by codewithvk** [comment]
@AkbarHabeeb Sorry i was busy with another project. But can you describe more?? I don't understand what should do.

**Comment by subhangi2731** [comment]
@AkbarHabeeb By today i will make the pr

**Comment by AkbarHabeeb** [comment]
We need to just add a Navbar with project name, please refer #17

**Comment by codewithvk** [comment]
I am doing this.

**Comment by Aaryan8751** [comment]
@AkbarHabeeb Could you please assign me this work?

**Comment by AkbarHabeeb** [comment]
Changes are already in review state #30 @Aaryan8751 Feel free to contribute to other issues

**Comment by AkbarHabeeb** [comment]
Duplicate
