### ISSUE TITLE
Add CSS support - 1

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/QP-Generator#46]
Move the textbox to the center of the row and make it looks good.

**Comment by Vishal-raj-1** [comment]
> Move the textbox to the center of the row and make it looks good.

Sure !! Could you please assign this issue to me 🔥

**Comment by tejaswini22199** [comment]
@AkbarHabeeb  which text box question1 box??

**Comment by AkbarHabeeb** [comment]
Yes @tejaswini22199

**Comment by priyanshi-2508** [comment]
Hello, I want to work on this issue under SWOC.

**Comment by AkbarHabeeb** [comment]
Plase go ahead @priyanshi-2508

**Comment by sanyajain26** [comment]
Hello, I would like to work on this issue.

**Comment by AkbarHabeeb** [comment]
Change in plan to have 2 columns for tha app.
