### ISSUE TITLE
Remove : Horizontal scroll bar

### ISSUE THREAD

**Issue by Vishal-raj-1** [Team-Tomato/QP-Generator#50]
**Describe the bug**
There is problem in Navbar. 

**Screenshots**

![navbar](https://user-images.githubusercontent.com/59874304/102011772-7c884600-3d6c-11eb-99ca-50cbe18a611b.JPG)

**Comment by AkbarHabeeb** [comment]
@Vishal-raj-1 Please head start it

**Comment by sj056** [comment]
Hey! I'm participant of SWOC. can I work on this issue or is it sorted?

**Comment by Vishal-raj-1** [comment]
@sj056 Please go ahead !!

**Comment by sj056** [comment]
@Vishal-raj-1 Sir can you please assign it to me So that I can send the PR?

**Comment by sj056** [comment]
@AkbarHabeeb Please assign me for the issue so that I can send the PR.

**Comment by sj056** [comment]
@AkbarHabeeb Sir I have sent the PR. Kindly review it.

**Comment by AkbarHabeeb** [comment]
#73
