### ISSUE TITLE
host

### ISSUE THREAD

**Issue by Ayush7614** [Team-Tomato/QP-Generator#6]
You can also host the project without hosting how people can know what is this

**Comment by AkbarHabeeb** [comment]
Can you please elaborate, the issue created lacks detailing.

**Comment by Ayush7614** [comment]
I mean you have not host the project brother

**Comment by AkbarHabeeb** [comment]
Yes, we didn't host it yet. We have planned to do once we have some measurable bandwidth of work was done. Thanks for sharing your view. 

For now, we can put this issue in Deferred state.
