### ISSUE TITLE
Mathbar not working properly

### ISSUE THREAD

**Issue by rsrkpatwari1234** [Team-Tomato/QP-Generator#67]
**Describe the bug**
When clicked, the add option of math bar, by default an equation appears.

**Expected behavior**
A  list of default maths operation should occur. Then we should get the option to add a new option or use the existing ones. If we are using some new maths function then it should get added to the default list of the math bar add option

**Comment by rsrkpatwari1234** [comment]
@AkbarHabeeb please review this issue and if applicable, please assign me score under njack iit patna

**Comment by AkbarHabeeb** [comment]
Thanks for your interest @rsrkpatwari1234. Sorry, its quite irrelevent
