### ISSUE TITLE
Changing the app title and logo

### ISSUE THREAD

**Issue by rsrkpatwari1234** [Team-Tomato/QP-Generator#68]
Currently, the page title is "React App" with the default logo of react. It is very important to change it.

**Comment by rsrkpatwari1234** [comment]
@AkbarHabeeb please review my issue and iff applicable provide me score for issue generation under njack iit patna. Also please assign me this issue to work on.

**Comment by AkbarHabeeb** [comment]
You are welcome

**Comment by jatinjain001** [comment]
I want to work on it , please assign it to me
