### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Ayush7614** [Team-Tomato/QP-Generator#7]
And please add some more interested and helpful readme if people can read the details of project then he can  know

**Comment by AkbarHabeeb** [comment]
Wish you had read our wiki page (https://github.com/Team-Tomato/QP-Generator/wiki) for project details @Ayush7614 
Let us know if u have any other questions

**Comment by Ayush7614** [comment]
Okk brother but with readme it will also very helpful that's why I raise the issue

**Comment by AkbarHabeeb** [comment]
Feel free to add them @Ayush7614, we can review the content and merge it :)

**Comment by AkbarHabeeb** [comment]
Merged the PR #13
