### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vrushti24** [Team-Tomato/QP-Generator#79]
**Is your feature request related to a problem? Please describe.**
I have came across your project and saw that it does not contain License

**Describe the solution you'd like**
I can add license like MIT license

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Its important to add license in your project

**Comment by Vrushti24** [comment]
I can work on this

**Comment by AkbarHabeeb** [comment]
Appreciate your interest. Currently, we decided to concentrate on code contribution

**Comment by Vrushti24** [comment]
Okayy...
