### ISSUE TITLE
Enhancement of README.md file

### ISSUE THREAD

**Issue by anirudhsai20** [Team-Tomato/QP-Generator#80]
The README.md file can be enhanced by adding a list all the Open Source programs in which this project has been listed in. Also it does not include a clear description of what the project is about. This needs to be added.

**Comment by anirudhsai20** [comment]
Hi! Please allow me to work on this issue under SWOC.

**Comment by AkbarHabeeb** [comment]
Appreciate your interest @anirudhsai20, we have a wiki page that describes the project in detail, please have a look at our wiki pages. And as of now, we are not looking for any doc-related changes. Thanks, please feel free to add code contributions
