### ISSUE TITLE
Code of Conduct and Readme Updation

### ISSUE THREAD

**Issue by Tejas1510** [Team-Tomato/QP-Generator#9]
I wish to add a formal code of conduct and Update the readme with getting started guide, and more feature a Readme also making it decorative so that it will be easier to understand 
I have gone through this https://github.com/Team-Tomato/QP-Generator/wiki but still the projects should have its proper Readme
so think of doing it
@AkbarHabeeb the decision lies with you
Thanks

**Comment by AkbarHabeeb** [comment]
Sounds good @Tejas1510 Feel free to send PR

**Comment by AkbarHabeeb** [comment]
Merged #13
